### ISSUE TITLE
libgen module unreliable

### ISSUE THREAD

**Issue by SargeKhan** [SargeKhan/aristotle#2]
Libgen module's .mirror function seldom behaves correctly,  sometimes it neither returns urlString nor an error and other times, after finding the urlString, somehow forgets it (Or am I doing something wrong? Attached log for the latter problemo 

```

box ~/P/W/aristotle$ node index.js                                                                                                                      {master} 
Mirror before checking
Didn't find an exisitng mirror
Mirror:
urlString:http://gen.lib.rus.ec
Scraping: http://gen.lib.rus.ec/get.php?md5=02390179884e954f7307866ebf718a27
DOWNLOAD LINK{"err":false,"result":"/get.php?md5=02390179884e954f7307866ebf718a27&key=GPTTHGDWHLE7JHEA"}
{ err: false,
  result: '/get.php?md5=02390179884e954f7307866ebf718a27&key=GPTTHGDWHLE7JHEA' }
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Invalid URI "undefined/get.php?md5=02390179884e954f7307866ebf718a27&key=GPTTHGDWHLE7JHEA"
    at Request.init (/home/usman/Projects/WebstormProjects/aristotle/node_modules/request/request.js:288:31)
    at new Request (/home/usman/Projects/WebstormProjects/aristotle/node_modules/request/request.js:142:8)
    at request (/home/usman/Projects/WebstormProjects/aristotle/node_modules/request/index.js:55:10)
    at Object.exports.saveFile (/home/usman/Projects/WebstormProjects/aristotle/libgenio.js:125:13)
    at /home/usman/Projects/WebstormProjects/aristotle/index.js:43:14
    at Request._callback (/home/usman/Projects/WebstormProjects/aristotle/libgenio.js:84:20)
    at Request.self.callback (/home/usman/Projects/WebstormProjects/aristotle/node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/usman/Projects/WebstormProjects/aristotle/node_modules/request/request.js:1046:10)
```

**Comment by haroondilshad** [comment]
I think this is not related to mirror. If you try to use the download function straight away, you can see we are using `mirror` global variable which is not yet initialized. We'll have to ensure that the global mirror is initialized whenever we want to access it

**Comment by SargeKhan** [comment]
```
exports.getDownloadLink = function(requestUrl, callback){
    console.log("Mirror before checking" + mirror);
    if(mirror){
        console.log("Mirror Link: " + mirror);
        scrape(mirror+"/get.php?md5="+requestUrl,callback);
    }
    else {
        console.log("Didn't find an exisitng mirror");
        libgen.mirror(function (err, urlString) {
            if(err || urlString == undefined){

                console.log("Problemo");
                return callback({
                    err: true,
                    result: err
                });
            }
            else{
                console.log("urlString:" + urlString);
                mirror = urlString;
                console.log(mirror);
                scrape(mirror+"/get.php?md5="+requestUrl,callback);
            }
        });
    }
};
```

download function first checks whether mirror variable is initialized or not. If it is, it calls the scrape method, otherwise goes ahead and searches for that mirror. Frankly, with this code, i am having trouble comprehending why the issue reported can occur. See if you can point it out. (Error can occur. just not this one)

**Comment by SargeKhan** [comment]
I am closing this issue since this repo is not actively maintained.
